site_name: Fomin Tools
theme:
  name: material
#  logo: images/logo_light.png  # Path relative to your docs directory
  logo: images/logos/fomin-tools-logo.svg
  favicon: images/logos/fomin-tools-logo.svg
  features:
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.path
    - navigation.tracking
#    - navigation.expand
    - navigation.top
#    - toc.integrate
    - content.code.copy
    - navigation.indexes  # This allows hiding navigation on index pages
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - css/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oleg-fomin
  favicon: images/favicon.png
plugins:
  - search
  - awesome-pages
extra_javascript:
  - assets/js/mermaid.min.js
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: 🔗
  - pymdownx.highlight
  - pymdownx.emoji
